
-- Criação da tabela principal que armazena todos os formulários
-- O campo 'data' armazena o JSON flexível de cada tipo de formulário
CREATE TABLE IF NOT EXISTS records (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  form_type TEXT NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  user_name TEXT,
  user_id TEXT,
  form_code TEXT,
  data JSONB
);

-- Tabela de Logs de Atividade
CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT,
  user_name TEXT,
  type TEXT,
  action TEXT,
  details TEXT,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de Usuários (simplificada para o exemplo, em produção usar Auth do Supabase)
CREATE TABLE IF NOT EXISTS users (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'OPERADOR',
  permissions JSONB DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS fruits (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE fruits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Fruits" ON fruits FOR ALL USING (true);
ALTER TABLE records ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso aberto (Para uso com chave Anon pública conforme configurado no frontend)
-- ATENÇÃO: Em produção real, restrinja estas políticas para authenticated users.
CREATE POLICY "Public Access Records" ON records FOR ALL USING (true);
CREATE POLICY "Public Access Logs" ON activity_logs FOR ALL USING (true);
CREATE POLICY "Public Access Users" ON users FOR ALL USING (true);
